### ISSUE TITLE
camera move too fast and clipping make strange part of model

### ISSUE THREAD

**Issue by tigrazone** [spnda/vk_gltf_viewer#3]
I use W S on keyboard for make model cleser/far and use center button of mouse for move model
look at video
https://github.com/spnda/vk_gltf_viewer/assets/3808839/dfdb9793-4fef-4a65-91ef-d85b65482a79

**Comment by spnda** [comment]
This is perfectly normal, since the model itself has a weird scale and is tiny compared to other models. If you open Sponza, Bistro, or other sample models you can see that movement is fine. The clipping is just because the far plane is set to 0.01f, which is usually enough but in the case of this model it makes it hard to show, as it's so tiny. I'm pushing a commit adding support for pre-defined cameras, which work perfectly with this model.

**Comment by tigrazone** [comment]
Select cameras saved with model is good option
