### ISSUE TITLE
How to get image name?

### ISSUE THREAD

**Issue by tigrazone** [spnda/vk_gltf_viewer#5]
I'm reading source
https://github.com/spnda/vk_gltf_viewer/blob/28b9209d8a574d090e91bb6c2a051b5660e133a9/src/main.cpp#L1227

Where is image name?
How to understand is image external or saved internally in gdb file?

**Comment by spnda** [comment]
I have no idea what you mean by "image name". Images could be stored within a GLB buffer, in an external file, or in a base64 buffer. As we pass LoadExternalImages to the loadGltf function, all images are loaded into a fastgltf::StaticVector (similar to a std::vector).

Also, to avoid any more issues with small simple questions perhaps you could join [this Discord server](https://discord.com/invite/Eb7P3wH) where I have a thread under "community-projects". You can ask me anything there, and theres other talented people who also know a thing or two.

**Comment by tigrazone** [comment]
I mean filename of image if it is not internal in glb file.
as i see in sources of submodules\fastgltf\include\fastgltf\types.hpp
```
    struct Image {
        DataSource data;

        FASTGLTF_STD_PMR_NS::string name;
    };
```
I mean access to "name" field of it struct Image from fg::Parser::parseImages().
As I see, name is filename without extension.
Also I add for debug before
https://github.com/spnda/fastgltf/blob/de4af9856c2d8f56549cfa551bde03d36c830882/src/fastgltf.cpp#L2325
```
		std::cout <<"uri "<<imageObject["uri"].get_string()<<std::endl;
		std::cout <<"mimeType "<<imageObject["mimeType"].get_string()<<std::endl;
		std::cout <<"name "<<imageObject["name"].get_string()<<std::endl;
```
For my task, I need understand mimeType for load dds, ktx which cant be loaded by stbi_load_from_memory().
Link to " join [this Discord server] " not added..

**Comment by spnda** [comment]
The name is just some name that the glTF provides, it has no value besides displaying that to the user. You need to look into the `data` field. That's a `std::variant` which holds a few different possibilities (just like a union). In your case, you'd need to look for `fastgltf::sources::URI`, which holds a URI object and a `mimeType`. Look up how to use std::variant or look at the gl_viewer or this example of how that's being accessed. Also, I added the Discord link I forgot to paste in.

**Comment by tigrazone** [comment]
show me in code how to get fastgltf::sources::URI and mimeType please

**Comment by spnda** [comment]
https://github.com/spnda/vk_gltf_viewer/blob/0a33c324fab87ead4704b26f28598e4c15d94826/src/main.cpp#L1254-L1280

This loads image data from an Array or a BufferView. Those are the only two cases since I currently specify `LoadExternalImages` which makes fastgltf load all files into memory while parsing. If you don't specify that, you'll instead have other cases, such as `URI`, `BufferView`, or  `ByteView` (when embedded in the GLB). There are plenty of online resources which show how to use `std::variant` using `std::get` and `std::visit`, so look at those for more details. If you just want to get the URI from any image, use this:
```cpp
auto& uri = std::get<fastgltf::sources::URI>(image.data);
// uri.uri is a fastgltf::URI, which could hold something like ./textures/tex.png
// uri.mimeType is the mime of the image (e.g. PNG, KTX, ...)
```
Note that this will throw an exception when `image.data` does not contain `sources::URI`, so look to `std::holds_alternative`, `std::get_if`, or `std::visit` to cover all cases. But, again, please look at online resources on this topic as this is not necessarily related to fastgltf, as it's just usage of a C++ standard container.
